import {
  Circle, Activity, Heart, Dumbbell, Bike, Footprints, PersonStanding, Volleyball, Trophy, Medal, Award,
  Brain, BookOpen, Book, BookMarked, Library, Pencil, PenTool, Edit3, GraduationCap, School, Languages, Calculator, Lightbulb,
  Briefcase, Laptop, Code, Code2, Terminal, Server, Database, GitBranch, Cpu, Globe, Globe2,
  Mail, MailOpen, Phone, MessageSquare, Send, Inbox,
  Calendar, CalendarDays, CalendarCheck, Clock, AlarmClock, Hourglass, Timer,
  Target, Crosshair, Flag, FlagTriangleRight, ListChecks, CheckCircle, CheckCircle2, ClipboardCheck, ClipboardList,
  Coffee, Apple, Utensils, UtensilsCrossed, GlassWater, Wine, Beer, Soup, Pizza, Salad, Carrot, Egg, Cookie, IceCream, Cake, Sandwich, Beef, EggFried, Croissant,
  Bed, Moon, MoonStar, Sunrise, Sun, Sunset, Cloud, CloudRain, CloudSnow, Snowflake, Umbrella, Rainbow,
  Music, Music2, Music3, Music4, Headphones, Camera, CameraOff, Image as ImageIcon, Palette, Brush, PaintBucket, Film, Clapperboard, Mic, Mic2, Guitar, Piano, Drum, Disc, Radio, Tv,
  Smile, Laugh, Heart as HeartIcon, HeartHandshake, MessageCircle, MessagesSquare, Users, User, UserCheck, UsersRound,
  Home, Building, Building2, Castle, Hotel, Tent, Warehouse,
  Flower, Flower2, Leaf, Sprout, TreePine, TreeDeciduous, Trees, Bird, Cat, Dog, Fish, Rabbit, Squirrel, Turtle, Bug, Worm, PawPrint,
  Wallet, PiggyBank, ShoppingBag, ShoppingCart, Gift, CreditCard, Banknote, Coins, DollarSign, Receipt,
  Sparkles, Star, Stars, Zap, Wind, Mountain, MountainSnow, Waves, Compass, Map, MapPin, Navigation, Tornado, Flame, Droplets, Droplet,
  Pill, Stethoscope, Bath, ShowerHead, Toilet, Eye, Glasses,
  Shirt, Scissors, Wrench, Hammer, Recycle, Trash2, Box, Package, Archive, Folder, FolderOpen,
  Plane, Car, Train, Bus, Ship, Sailboat, Rocket, Anchor, Bike as BikeIcon2,
  Gamepad, Gamepad2, Dices, Puzzle, Joystick,
  Feather, Wand2, Crown, Gem, Key, Lock, Unlock, Shield, ShieldCheck, Bell, BellRing, Bookmark, Tag, Tags,
  Pin, Paperclip, Link, Link2, Hash, AtSign, Percent,
  Newspaper, FileText, Files, FileCode, FilePen, NotebookPen, Notebook, StickyNote,
  BarChart, BarChart2, BarChart3, LineChart, PieChart, TrendingUp, TrendingDown, Activity as ActivityIcon,
  Settings, SlidersHorizontal, Filter, Search, ZoomIn,
  Plus, Minus, X, Check, ArrowUp, ArrowDown, ArrowRight, ArrowLeft,
  type LucideIcon,
} from "lucide-react";

export type HabitIconDef = { name: string; label: string; icon: LucideIcon };
export type HabitIconGroup = { label: string; icons: HabitIconDef[] };

export const HABIT_ICON_GROUPS: HabitIconGroup[] = [
  {
    label: "Sağlık & Spor",
    icons: [
      { name: "heart", label: "Kalp", icon: Heart },
      { name: "activity", label: "Aktivite", icon: Activity },
      { name: "dumbbell", label: "Ağırlık", icon: Dumbbell },
      { name: "bike", label: "Bisiklet", icon: Bike },
      { name: "footprints", label: "Yürüyüş", icon: Footprints },
      { name: "person-standing", label: "Esneme", icon: PersonStanding },
      { name: "volleyball", label: "Top", icon: Volleyball },
      { name: "pill", label: "İlaç", icon: Pill },
      { name: "stethoscope", label: "Sağlık", icon: Stethoscope },
      { name: "bath", label: "Banyo", icon: Bath },
      { name: "shower", label: "Duş", icon: ShowerHead },
      { name: "trophy", label: "Kupa", icon: Trophy },
      { name: "medal", label: "Madalya", icon: Medal },
      { name: "award", label: "Ödül", icon: Award },
      { name: "eye", label: "Göz", icon: Eye },
      { name: "glasses", label: "Gözlük", icon: Glasses },
    ],
  },
  {
    label: "Zihin & Çalışma",
    icons: [
      { name: "brain", label: "Beyin", icon: Brain },
      { name: "lightbulb", label: "Fikir", icon: Lightbulb },
      { name: "book-open", label: "Okuma", icon: BookOpen },
      { name: "book", label: "Kitap", icon: Book },
      { name: "book-marked", label: "Yer İmi", icon: BookMarked },
      { name: "library", label: "Kütüphane", icon: Library },
      { name: "pencil", label: "Yazma", icon: Pencil },
      { name: "pen-tool", label: "Kalem", icon: PenTool },
      { name: "edit", label: "Düzenle", icon: Edit3 },
      { name: "graduation-cap", label: "Eğitim", icon: GraduationCap },
      { name: "school", label: "Okul", icon: School },
      { name: "languages", label: "Dil", icon: Languages },
      { name: "calculator", label: "Hesap", icon: Calculator },
      { name: "briefcase", label: "İş", icon: Briefcase },
      { name: "laptop", label: "Laptop", icon: Laptop },
      { name: "code", label: "Kod", icon: Code },
      { name: "code-2", label: "Kod 2", icon: Code2 },
      { name: "terminal", label: "Terminal", icon: Terminal },
      { name: "server", label: "Sunucu", icon: Server },
      { name: "database", label: "Veritabanı", icon: Database },
      { name: "git-branch", label: "Git", icon: GitBranch },
      { name: "cpu", label: "İşlemci", icon: Cpu },
      { name: "globe", label: "Dünya", icon: Globe },
      { name: "globe-2", label: "Küre", icon: Globe2 },
    ],
  },
  {
    label: "İletişim",
    icons: [
      { name: "mail", label: "Mail", icon: Mail },
      { name: "mail-open", label: "Mail Açık", icon: MailOpen },
      { name: "inbox", label: "Gelen Kutusu", icon: Inbox },
      { name: "send", label: "Gönder", icon: Send },
      { name: "phone", label: "Telefon", icon: Phone },
      { name: "message-circle", label: "Sohbet", icon: MessageCircle },
      { name: "message-square", label: "Mesaj", icon: MessageSquare },
      { name: "messages-square", label: "Mesajlar", icon: MessagesSquare },
      { name: "users", label: "Topluluk", icon: Users },
      { name: "users-round", label: "Grup", icon: UsersRound },
      { name: "user", label: "Kullanıcı", icon: User },
      { name: "user-check", label: "Onaylı", icon: UserCheck },
      { name: "smile", label: "Gülümse", icon: Smile },
      { name: "laugh", label: "Gülüş", icon: Laugh },
      { name: "heart-handshake", label: "Dostluk", icon: HeartHandshake },
      { name: "at-sign", label: "@", icon: AtSign },
    ],
  },
  {
    label: "Yemek & İçecek",
    icons: [
      { name: "coffee", label: "Kahve", icon: Coffee },
      { name: "glass-water", label: "Su", icon: GlassWater },
      { name: "wine", label: "Şarap", icon: Wine },
      { name: "beer", label: "Bira", icon: Beer },
      { name: "apple", label: "Meyve", icon: Apple },
      { name: "carrot", label: "Sebze", icon: Carrot },
      { name: "salad", label: "Salata", icon: Salad },
      { name: "soup", label: "Çorba", icon: Soup },
      { name: "egg", label: "Yumurta", icon: Egg },
      { name: "egg-fried", label: "Sahanda", icon: EggFried },
      { name: "utensils", label: "Yemek", icon: Utensils },
      { name: "utensils-crossed", label: "Çatal Bıçak", icon: UtensilsCrossed },
      { name: "pizza", label: "Pizza", icon: Pizza },
      { name: "sandwich", label: "Sandviç", icon: Sandwich },
      { name: "beef", label: "Et", icon: Beef },
      { name: "cookie", label: "Kurabiye", icon: Cookie },
      { name: "ice-cream", label: "Dondurma", icon: IceCream },
      { name: "cake", label: "Pasta", icon: Cake },
      { name: "croissant", label: "Kruvasan", icon: Croissant },
    ],
  },
  {
    label: "Uyku & Doğa",
    icons: [
      { name: "bed", label: "Yatak", icon: Bed },
      { name: "moon", label: "Ay", icon: Moon },
      { name: "moon-star", label: "Ay & Yıldız", icon: MoonStar },
      { name: "sun", label: "Güneş", icon: Sun },
      { name: "sunrise", label: "Şafak", icon: Sunrise },
      { name: "sunset", label: "Gün Batımı", icon: Sunset },
      { name: "cloud", label: "Bulut", icon: Cloud },
      { name: "cloud-rain", label: "Yağmur", icon: CloudRain },
      { name: "cloud-snow", label: "Kar", icon: CloudSnow },
      { name: "snowflake", label: "Kar Tanesi", icon: Snowflake },
      { name: "umbrella", label: "Şemsiye", icon: Umbrella },
      { name: "rainbow", label: "Gökkuşağı", icon: Rainbow },
      { name: "leaf", label: "Yaprak", icon: Leaf },
      { name: "sprout", label: "Filiz", icon: Sprout },
      { name: "flower", label: "Çiçek", icon: Flower },
      { name: "flower-2", label: "Lale", icon: Flower2 },
      { name: "tree-pine", label: "Çam", icon: TreePine },
      { name: "tree-deciduous", label: "Ağaç", icon: TreeDeciduous },
      { name: "trees", label: "Orman", icon: Trees },
      { name: "mountain", label: "Dağ", icon: Mountain },
      { name: "mountain-snow", label: "Karlı Dağ", icon: MountainSnow },
      { name: "waves", label: "Dalga", icon: Waves },
      { name: "wind", label: "Rüzgar", icon: Wind },
      { name: "tornado", label: "Hortum", icon: Tornado },
      { name: "flame", label: "Alev", icon: Flame },
      { name: "droplet", label: "Damla", icon: Droplet },
      { name: "droplets", label: "Damlalar", icon: Droplets },
    ],
  },
  {
    label: "Yaratıcılık & Eğlence",
    icons: [
      { name: "music", label: "Müzik", icon: Music },
      { name: "music-2", label: "Nota 2", icon: Music2 },
      { name: "music-3", label: "Nota 3", icon: Music3 },
      { name: "music-4", label: "Nota 4", icon: Music4 },
      { name: "headphones", label: "Kulaklık", icon: Headphones },
      { name: "guitar", label: "Gitar", icon: Guitar },
      { name: "piano", label: "Piyano", icon: Piano },
      { name: "drum", label: "Davul", icon: Drum },
      { name: "disc", label: "Plak", icon: Disc },
      { name: "radio", label: "Radyo", icon: Radio },
      { name: "tv", label: "TV", icon: Tv },
      { name: "mic", label: "Mikrofon", icon: Mic },
      { name: "mic-2", label: "Mikrofon 2", icon: Mic2 },
      { name: "camera", label: "Kamera", icon: Camera },
      { name: "image", label: "Resim", icon: ImageIcon },
      { name: "film", label: "Film", icon: Film },
      { name: "clapperboard", label: "Klaket", icon: Clapperboard },
      { name: "palette", label: "Palet", icon: Palette },
      { name: "brush", label: "Fırça", icon: Brush },
      { name: "paint-bucket", label: "Boya", icon: PaintBucket },
      { name: "feather", label: "Tüy", icon: Feather },
      { name: "wand", label: "Asa", icon: Wand2 },
      { name: "gamepad", label: "Oyun", icon: Gamepad },
      { name: "gamepad-2", label: "Kontrol", icon: Gamepad2 },
      { name: "joystick", label: "Joystick", icon: Joystick },
      { name: "dices", label: "Zar", icon: Dices },
      { name: "puzzle", label: "Yapboz", icon: Puzzle },
    ],
  },
  {
    label: "Hayvanlar",
    icons: [
      { name: "cat", label: "Kedi", icon: Cat },
      { name: "dog", label: "Köpek", icon: Dog },
      { name: "bird", label: "Kuş", icon: Bird },
      { name: "fish", label: "Balık", icon: Fish },
      { name: "rabbit", label: "Tavşan", icon: Rabbit },
      { name: "squirrel", label: "Sincap", icon: Squirrel },
      { name: "turtle", label: "Kaplumbağa", icon: Turtle },
      { name: "bug", label: "Böcek", icon: Bug },
      { name: "worm", label: "Solucan", icon: Worm },
      { name: "paw-print", label: "Pati", icon: PawPrint },
    ],
  },
  {
    label: "Manevi & Namaz",
    icons: [
      { name: "hilal", label: "Hilal", icon: MoonStar },
      { name: "sabah", label: "Sabah", icon: Sunrise },
      { name: "ogle", label: "Öğle", icon: Sun },
      { name: "aksam", label: "Akşam", icon: Sunset },
      { name: "yatsi", label: "Yatsı", icon: Moon },
      { name: "yildiz", label: "Yıldız", icon: Star },
      { name: "dua", label: "Dua", icon: Heart },
      { name: "zikir", label: "Zikir", icon: Sparkles },
      { name: "kuran", label: "Kuran", icon: BookOpen },
      { name: "vakit", label: "Vakit", icon: Timer },
      { name: "hatirlatma", label: "Hatırlatma", icon: AlarmClock },
      { name: "kible", label: "Kıble", icon: Compass },
    ],
  },
  {
    label: "Seyahat & Mekan",
    icons: [
      { name: "home", label: "Ev", icon: Home },
      { name: "building", label: "Bina", icon: Building },
      { name: "building-2", label: "Ofis", icon: Building2 },
      { name: "castle", label: "Kale", icon: Castle },
      { name: "hotel", label: "Otel", icon: Hotel },
      { name: "tent", label: "Çadır", icon: Tent },
      { name: "warehouse", label: "Depo", icon: Warehouse },
      { name: "plane", label: "Uçak", icon: Plane },
      { name: "car", label: "Araba", icon: Car },
      { name: "train", label: "Tren", icon: Train },
      { name: "bus", label: "Otobüs", icon: Bus },
      { name: "ship", label: "Gemi", icon: Ship },
      { name: "sailboat", label: "Yelkenli", icon: Sailboat },
      { name: "rocket", label: "Roket", icon: Rocket },
      { name: "anchor", label: "Çapa", icon: Anchor },
      { name: "compass", label: "Pusula", icon: Compass },
      { name: "map", label: "Harita", icon: Map },
      { name: "map-pin", label: "Konum", icon: MapPin },
      { name: "navigation", label: "Yön", icon: Navigation },
    ],
  },
  {
    label: "Para & Alışveriş",
    icons: [
      { name: "wallet", label: "Cüzdan", icon: Wallet },
      { name: "piggy-bank", label: "Birikim", icon: PiggyBank },
      { name: "credit-card", label: "Kart", icon: CreditCard },
      { name: "banknote", label: "Banknot", icon: Banknote },
      { name: "coins", label: "Bozukluk", icon: Coins },
      { name: "dollar-sign", label: "Dolar", icon: DollarSign },
      { name: "receipt", label: "Fatura", icon: Receipt },
      { name: "shopping-bag", label: "Çanta", icon: ShoppingBag },
      { name: "shopping-cart", label: "Sepet", icon: ShoppingCart },
      { name: "gift", label: "Hediye", icon: Gift },
      { name: "tag", label: "Etiket", icon: Tag },
      { name: "tags", label: "Etiketler", icon: Tags },
    ],
  },
  {
    label: "Hedef & Plan",
    icons: [
      { name: "target", label: "Hedef", icon: Target },
      { name: "crosshair", label: "Nişan", icon: Crosshair },
      { name: "flag", label: "Bayrak", icon: Flag },
      { name: "flag-triangle", label: "Üçgen", icon: FlagTriangleRight },
      { name: "list-checks", label: "Liste", icon: ListChecks },
      { name: "check-circle", label: "Onay", icon: CheckCircle },
      { name: "check-circle-2", label: "Onay 2", icon: CheckCircle2 },
      { name: "clipboard-check", label: "Pano Onay", icon: ClipboardCheck },
      { name: "clipboard-list", label: "Pano Liste", icon: ClipboardList },
      { name: "calendar", label: "Takvim", icon: Calendar },
      { name: "calendar-days", label: "Günler", icon: CalendarDays },
      { name: "calendar-check", label: "Tamam", icon: CalendarCheck },
      { name: "clock", label: "Saat", icon: Clock },
      { name: "alarm-clock", label: "Alarm", icon: AlarmClock },
      { name: "hourglass", label: "Kum Saati", icon: Hourglass },
      { name: "timer", label: "Kronometre", icon: Timer },
      { name: "trending-up", label: "Yükseliş", icon: TrendingUp },
      { name: "trending-down", label: "Düşüş", icon: TrendingDown },
      { name: "bar-chart", label: "Sütun", icon: BarChart },
      { name: "bar-chart-2", label: "Sütun 2", icon: BarChart2 },
      { name: "bar-chart-3", label: "Sütun 3", icon: BarChart3 },
      { name: "line-chart", label: "Çizgi", icon: LineChart },
      { name: "pie-chart", label: "Pasta", icon: PieChart },
    ],
  },
  {
    label: "Belge & Not",
    icons: [
      { name: "file-text", label: "Belge", icon: FileText },
      { name: "files", label: "Belgeler", icon: Files },
      { name: "file-code", label: "Kod Belgesi", icon: FileCode },
      { name: "file-pen", label: "Düzenle", icon: FilePen },
      { name: "notebook", label: "Defter", icon: Notebook },
      { name: "notebook-pen", label: "Yazılı Defter", icon: NotebookPen },
      { name: "sticky-note", label: "Yapıştır", icon: StickyNote },
      { name: "newspaper", label: "Gazete", icon: Newspaper },
      { name: "folder", label: "Klasör", icon: Folder },
      { name: "folder-open", label: "Klasör Açık", icon: FolderOpen },
      { name: "archive", label: "Arşiv", icon: Archive },
      { name: "box", label: "Kutu", icon: Box },
      { name: "package", label: "Paket", icon: Package },
      { name: "bookmark", label: "Yer İmi", icon: Bookmark },
      { name: "pin", label: "İğne", icon: Pin },
      { name: "paperclip", label: "Ataç", icon: Paperclip },
      { name: "link", label: "Bağlantı", icon: Link },
      { name: "link-2", label: "Zincir", icon: Link2 },
      { name: "hash", label: "Hashtag", icon: Hash },
    ],
  },
  {
    label: "Ev & Diğer",
    icons: [
      { name: "shirt", label: "Giyim", icon: Shirt },
      { name: "scissors", label: "Makas", icon: Scissors },
      { name: "wrench", label: "Tamir", icon: Wrench },
      { name: "hammer", label: "Çekiç", icon: Hammer },
      { name: "recycle", label: "Geri Dönüşüm", icon: Recycle },
      { name: "settings", label: "Ayarlar", icon: Settings },
      { name: "sliders", label: "Filtreler", icon: SlidersHorizontal },
      { name: "key", label: "Anahtar", icon: Key },
      { name: "lock", label: "Kilit", icon: Lock },
      { name: "unlock", label: "Açık", icon: Unlock },
      { name: "shield", label: "Kalkan", icon: Shield },
      { name: "shield-check", label: "Güvenli", icon: ShieldCheck },
      { name: "bell", label: "Çan", icon: Bell },
      { name: "bell-ring", label: "Çalan Çan", icon: BellRing },
      { name: "crown", label: "Taç", icon: Crown },
      { name: "gem", label: "Mücevher", icon: Gem },
      { name: "sparkles", label: "Parıltı", icon: Sparkles },
      { name: "star", label: "Yıldız", icon: Star },
      { name: "stars", label: "Yıldızlar", icon: Stars },
      { name: "zap", label: "Enerji", icon: Zap },
      { name: "circle", label: "Daire", icon: Circle },
    ],
  },
];

const FLAT: Record<string, LucideIcon> = HABIT_ICON_GROUPS.reduce((acc, g) => {
  g.icons.forEach((i) => { acc[i.name] = i.icon; });
  return acc;
}, {} as Record<string, LucideIcon>);

export const getHabitIcon = (name?: string | null): LucideIcon => FLAT[name || "circle"] || Circle;
